### ISSUE TITLE
appimaged and AppImageLauncher are mutually exclusive

### ISSUE THREAD

**Issue by probonopd** [rauldipeas/Unity-XP#12]
Thanks for making a great AppImage experience out of the box!

Please note that appimaged and AppImageLauncher are mutually exclusive, which means that only one of them (but not both) should be installed.

* appimaged if you don't want any on-screen dialog boxes
* AppImageLauncher if you want on-screen dialog boxes ("do you want to move this AppImage to $HOME/Applications...?")

https://github.com/rauldipeas/Unity-XP/blob/6d109bdb6bf5e4b45f4fd7bf54b0480d8fdbc863/code/build.sh#L192

**Comment by rauldipeas** [comment]
I'm glad that you ask.

I keep both because i want all of these behaviours integrated.

If you download an AppImage, it will be showed on Unity dash instantly, at launch, you will be asked, but if you don't want to move file, it will be preserve in place, and if you install it from Pling store, it'll go directly to correctly folder, thanks to OCS-URL.

Those 3 apps are necessary to provide this AppImage integration.

**Comment by chdslv** [comment]
@rauldipeas 
I suppose, @probonopd would know more about AppImage as it is his baby.
